---
- hosts: logsAz
  become: yes
  vars:
    kib_ver: kibana-5.5.2-linux-x86_64
    kib_dir: /opt/kibana
    
  tasks:
    - name: install default-jre
      apt:
        name: default-jre
        state: present
    - name: create kibana user
      user:
        name: kibana
        password: $6$hHW/.C5XD$xv.hTpKCKWPoa4yT.wOxVtvADKfNNYTZjhwmsoG5DZiNH3A3mar2rHCvJsJnkobmlb73qTLsr6ZWRs7umTL4P0
        createhome: no
        state: present
    - name: extract kibana tar.gz
      unarchive:
        src: ../tar/{{ kib_ver }}.tar.gz
        dest: /opt/
        owner: kibana
        group: kibana
    - name: rename extracted tar to 'kibana'
      command: mv /opt/{{ kib_ver }} {{ kib_dir }}
    - name: copy kibana.yml
      template:
        src: ../conf/kibana.yml.j2
        dest: "{{ kib_dir }}/config/kibana.yml"
        owner: kibana
        group: kibana
        mode: 0644
        backup: yes
    - name: copy systemd kibana.service
      template:
        src: ../systemd/kibana.service.j2
        dest: /lib/systemd/system/kibana.service
        owner: root
        group: root
        mode: 0644
        backup: no
    - name: enable kibana.service
      systemd:
        daemon_reload: yes
        name: kibana
        enabled: yes
        masked: no
    - name: start kibana.service
      systemd:
        name: kibana
        state: started
