---
- hosts: logsAz
  become: yes
  vars:
    none: none

  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: copy nginx.conf
      template:
        src: ../conf/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify:
      - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
