---
- hosts: trans0
  become: yes
  vars:
    none: none

  tasks:
    - name: install samba
      apt:
        name: samba
        state: present
    - name: copy smb.conf
      template:
        src: ../conf/smb.conf.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify:
      - restart smbd
      - restart nmbd

  handlers:
    - name: restart smbd
      service:
        name: smbd
        state: restarted
    - name: restart nmbd
      service:
        name: nmbd
        state: restarted
