---
- hosts: dml0
  become: yes
  vars:
    statsd_ver: statsd_exporter-0.4.0.linux-amd64
    statsd_dir: /opt/statsd_exporter

  tasks:
    - name: extract statsd_exporter tar.gz
      unarchive:
        src: ../tar/{{ statsd_ver }}.tar.gz
        dest: /opt/
        owner: root
        group: root
    - name: rename extracted tar to 'statsd_exporter'
      command: mv /opt/{{ statsd_ver }} {{ statsd_dir }}
    - name: copy statsd_mapping.conf
      template:
        src: ../conf/statsd_mapping.conf
        dest: "{{ statsd_dir }}/statsd_mapping.conf"
        owner: root
        group: root
        mode: 0644
        backup: yes
    - name: copy systemd statsd_exporter.service
      template:
        src: ../systemd/statsd_exporter.service.j2
        dest: /lib/systemd/system/statsd_exporter.service
        owner: root
        group: root
        mode: 0644
        backup: no
    - name: enable statsd_exporter.service
      systemd:
        daemon_reload: yes
        name: statsd_exporter
        enabled: yes
        masked: no
    - name: start statsd_exporter.service
      systemd:
        name: statsd_exporter
        state: started