---
- hosts: logsAz
  become: yes
  vars:
    es_ver: elasticsearch-5.5.2
    es_dir: /opt/elasticsearch
    
  tasks:
    - name: install default-jre
      apt:
        name: default-jre
        state: present
    - name: create elasticsearch user
      user:
        name: elasticsearch
        password: $6$hHW/.C5XD$xv.hTpKCKWPoa4yT.wOxVtvADKfNNYTZjhwmsoG5DZiNH3A3mar2rHCvJsJnkobmlb73qTLsr6ZWRs7umTL4P0
        createhome: no
        state: present
    - name: extract elasticsearch tar.gz
      unarchive:
        src: ../tar/{{ es_ver }}.tar.gz
        dest: /opt/
        owner: elasticsearch
        group: elasticsearch
    - name: rename extracted tar to 'elasticsearch'
      command: mv /opt/{{ es_ver }} {{ es_dir }}
    - name: copy elasticsearch.yml
      template:
        src: ../conf/elasticsearch.yml.j2
        dest: "{{ es_dir }}/config/elasticsearch.yml"
        owner: elasticsearch
        group: elasticsearch
        mode: 0644
        backup: yes
    - name: copy systemd elasticsearch.service
      template:
        src: ../systemd/elasticsearch.service.j2
        dest: /lib/systemd/system/elasticsearch.service
        owner: root
        group: root
        mode: 0644
        backup: no
    - name: enable elasticsearch.service
      systemd:
        daemon_reload: yes
        name: elasticsearch
        enabled: yes
        masked: no
    - name: start elasticsearch.service
      systemd:
        name: elasticsearch
        state: started
